index:
    path: /
    defaults: { _controller: 'BAB\Controller\DefaultController' }

upload:
    path: /upload
    defaults: { _controller: 'BAB\Controller\UploadController' }
    condition: "request.isXmlHttpRequest()"
    methods: ['POST']
