index:
    path: /
    controller: 'BAB\Controller\DefaultController'

upload:
    path: /upload
    controller: 'BAB\Controller\UploadController'
    condition: "request.isXmlHttpRequest()"
    methods: ['POST']

play_on_pi:
    path: /on-pi
    controller: 'BAB\Controller\PlayerController'
    condition: "request.isXmlHttpRequest()"
    methods: ['POST']
