index:
    path: /
    controller: 'BAB\Controller\DefaultController'

upload:
    path: /upload
    controller: 'BAB\Controller\UploadController'
    condition: "request.isXmlHttpRequest()"
    methods: ['POST']
