parameters:
    max_played: 50
    public_path: '%kernel.project_dir%/public'
    dsn: '%env(resolve:DATABASE_URL)%'
    command: '%env(PLAYER_COMMAND)%'
    env(CRON_TIME): 5

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $publicPath: '%public_path%'

    BAB\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Model,Repository,Tests}'

    BAB\Service\Player:
        $command: '%command%'
        $maxPlayed: '%max_played%'
    BAB\Manager\SqliteManager: ['%dsn%']

    BAB\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    BAB\Controller\PlayerController:
        arguments:
            $secret: '%env(APP_SECRET)%'
        tags: ['controller.service_arguments']
