parameters:
    max_played: 50
    allowed_formats: ['mp3', 'wav', 'ogg']

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BAB\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Model,Repository,Tests}'

    BAB\Service\Utils: ['%kernel.project_dir%']
    BAB\Service\Finder:
        $allowedFormats: '%allowed_formats%'
    BAB\Service\Player:
        $command: '%command%'
        $maxPlayed: '%max_played%'

    BAB\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
